export const constants = {
    HUB_URL: window["__BASE_URL__"],
    STORAGE_KEY: "[NoDaysOffApp] STORAGE_KEY",
    ACCESS_TOKEN_KEY: "ACCESS_TOKEN_KEY",
    LOGIN_CREDENTIALS: "LOGIN_CREDENTIALS",
    CURRENT_PROFILE_KEY: "CURRENT_PROFILE_KEY",
    CURRENT_TEAM_KEY: "CURRENT_TEAM_KEY",
    TENANT: "TENANT",
    TILES:"TILES",
    CORRELATION_IDS_KEY: "CORRELATION_IDS_KEY",
    CURRENT_USER_KEY: "CURRENT_USER_KEY",
    DASHBOARD_TILES: "DASHBOARD_TILES",
    DASHBOARD_COLUMN_WIDTH: 120,
    DASHBOARD_ROW_HEIGHT: 90
};

