// <auto-generated />
using System;
using Athletes.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Athletes.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AthletesDbContext))]
    [Migration("20260125172818_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Athletes.Core.Aggregates.Athlete.AthleteWeight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AthleteId")
                        .HasColumnType("int");

                    b.Property<string>("RecordedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("WeighedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("WeightInKgs")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AthleteId");

                    b.ToTable("AthleteWeights", (string)null);
                });

            modelBuilder.Entity("Athletes.Core.Aggregates.Athlete.CompletedExercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AthleteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CompletionDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Distance")
                        .HasColumnType("int");

                    b.Property<string>("RecordedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Reps")
                        .HasColumnType("int");

                    b.Property<int>("ScheduledExerciseId")
                        .HasColumnType("int");

                    b.Property<int>("Sets")
                        .HasColumnType("int");

                    b.Property<int>("TimeInSeconds")
                        .HasColumnType("int");

                    b.Property<int>("WeightInKgs")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AthleteId");

                    b.ToTable("CompletedExercises", (string)null);
                });

            modelBuilder.Entity("Athletes.Core.Aggregates.Profile.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int?>("TenantId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Profiles", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Athletes.Core.Aggregates.Athlete.Athlete", b =>
                {
                    b.HasBaseType("Athletes.Core.Aggregates.Profile.Profile");

                    b.Property<int?>("CurrentWeight")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastWeighedOn")
                        .HasColumnType("datetime2");

                    b.ToTable("Athletes", (string)null);
                });

            modelBuilder.Entity("Athletes.Core.Aggregates.Athlete.AthleteWeight", b =>
                {
                    b.HasOne("Athletes.Core.Aggregates.Athlete.Athlete", null)
                        .WithMany("Weights")
                        .HasForeignKey("AthleteId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Athletes.Core.Aggregates.Athlete.CompletedExercise", b =>
                {
                    b.HasOne("Athletes.Core.Aggregates.Athlete.Athlete", null)
                        .WithMany("CompletedExercises")
                        .HasForeignKey("AthleteId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Athletes.Core.Aggregates.Athlete.Athlete", b =>
                {
                    b.HasOne("Athletes.Core.Aggregates.Profile.Profile", null)
                        .WithOne()
                        .HasForeignKey("Athletes.Core.Aggregates.Athlete.Athlete", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Athletes.Core.Aggregates.Athlete.Athlete", b =>
                {
                    b.Navigation("CompletedExercises");

                    b.Navigation("Weights");
                });
#pragma warning restore 612, 618
        }
    }
}
